- name: "create directories"
  file:
    path: "{{ item }}"
    state: directory
    mode:  0755
    owner: root
    group: root
  loop:
  - /etc/fcos-sync

- name: "create config file if does not exist"
  template:
    src:   "{{ item | basename }}.jinja2"
    dest:  "{{ item }}"
    owner: root
    group: root
    mode:  0644
    #force: no      # if the file exists we do nothing
  loop:
  - "/etc/fcos-sync/fcos-sync.conf"

- name: "install fcos scripts for external sync"
  copy:
    src:  "{{ item }}"
    dest: "/usr/local/bin/{{ item|basename }}"
    owner: root
    group: root
    mode:  0755
  loop:
  - "fcos-download-simple.sh"
  - "fcos-latest-version.sh" 
  - "fcos-sync-external.sh"
  when: 
  -  inventory_hostname == ansible_play_hosts_all[0]

- name: Remove files if they exist on the other hosts
  ansible.builtin.file:
    path: "/usr/local/bin/{{ item|basename }}"
    state: absent
  loop:
  - "fcos-download-simple.sh"
  - "fcos-latest-version.sh"
  - "fcos-sync-external.sh"
  when:
  -  inventory_hostname != ansible_play_hosts_all[0]


- name: "install fcos scripts for local sync"
  copy:
    src:  "{{ item }}"
    dest: "/usr/local/bin/{{ item|basename }}"
    owner: root
    group: root
    mode:  0755
  loop:
  - "fcos-unpack.sh"
  - "fcos-sync-local.sh"

