# check if hosts are available
# check if scripts for software install has run already
# continous run it on hosts where the install failed until success ... or 10 retry has failed.
# check if it has successfully run again for 10 seconds

# https://stackoverflow.com/questions/39800368/test-if-a-server-is-reachable-from-host-and-has-port-open-with-ansible
- wait_for:
    host:    "{{ ansible_host }}"
    port:    22
    timeout: 30
  retries: 10  # 30 * 10 = 300 secs = 5 Minutes
  register: result
  until:  result is succeeded
  delegate_to: localhost

# FIXME might not work, if system cannot install python, the "command" will not work
# https://stackoverflow.com/questions/44134642/how-to-retry-ansible-task-that-may-fail
#- command: /usr/bin/false
- command: systemctl start package-installer.service
  retries: 3
  delay: 3
  register: result
  until: result.rc == 0

