- name:   test if mandatory attributes for proxmox virtual machines exist
  action: proxmox-init-validate

- action: process_flash_list


- name: "show flash hosts" 
  debug:
    msg: "{{ flash }}"
  when: "flash is defined and flash"

#- fail:
#   msg: "STOP!"

- debug:
    msg: "{{ ansible_host }}"

