---
#- hosts:
#  - fedora_coreos
#  roles:
#  - hosts

- hosts:
  - proxmox
  roles:
  - fcos

#- hosts:
#  - all
#  vars:
#  - namespace: fritz.box
#  roles:
#  - localtime

#  - rpmfusion 
#  - wireguard-client

#  - sudo
#  - certificates
#  - dnf-automatic
#  - packages
#  - fail2ban

#  - dietmar
#  - gitlab-runner
#  - network
#  - nfs
#  - openvpn
#  - samba
#  - snapshot
#  - sssd
#  - sysctl
#  - systemd
#  - zsh


##  - docker 

