- gather_facts:     False
  any_errors_fatal: True
  roles:
  - ansible-validation
  hosts:
  - localhost

- name: Configure proxmox hosts
  roles:
  - proxmox-hosts
  hosts:
  - proxmox_hosts
  tags:
  - proxmox-hosts

- name: install fcos sync
  roles:
  - fcos-sync
  hosts:
  - proxmox_hosts
  tags:
  - fcos-sync

- name: install fedora-cloud sync
  roles:
  - fedora-cloud-sync
  hosts:
  - proxmox_hosts
  tags:
  - fedora-cloud-sync

- name: install fedora-container sync
  roles:
  - fedora-container-sync
  hosts:
  - proxmox_hosts
  tags:
  - fedora-container-sync
