- gather_facts:     False
  any_errors_fatal: True
  roles:
  - ansible-validation
  hosts:
  - localhost

- name: proxmox flash fcos
  roles:
  - proxmox-hosts
  hosts:
  - proxmox_hosts
  tags:
  - proxmox-hosts

- name: install fcos sync
  roles:
  - fcos-sync
  hosts:
  - proxmox_hosts
  tags:
  - fcos-sync
