- hosts:
  - localhost
  gather_facts:     False
  any_errors_fatal: True
  roles:
  - ansible-validation

- name: proxmox flash fcos
  hosts:
  - proxmox_hosts
  roles:
  - proxmox-create-guests

- name: prepare k8s
  hosts:
  - fedora_coreos_machines
  gather_facts:     False
  any_errors_fatal: True
  roles:
  - proxmox-prepare-k8s
