- hosts:
  - localhost
  gather_facts:     False
  any_errors_fatal: True
  roles:
  - ansible-validation

- name: proxmox flash fcos
  hosts:
  - proxmox_hosts
  roles:
  - proxmox-create-guests




- name: create group dynamic_fedora_coreos_machines from group fedora_coreos_machines
  hosts:
  - localhost
  gather_facts:     False
  any_errors_fatal: True
  roles:
  - fcos-group
  tags:
  - group 
  - packages
  - quirks

- name: prepare k8s
  hosts:
  - dynamic_fedora_coreos_machines
  gather_facts:     False
  any_errors_fatal: True
  roles:
  - proxmox-prepare-k8s
  tags:
  - packages

- name: apply quirks
  hosts:
  - dynamic_fedora_coreos_machines
  roles:
  - fcos-quirks
  tags:
  - quirks
