---
- hosts:
  - localhost
  gather_facts:     False
  any_errors_fatal: True
  roles:
  - ansible-validation

- name: proxmox flash fcos
  roles:
  - proxmox-create-guests
  hosts:
  - proxmox_hosts
- name: install keepalived
  roles:
  - highavailability
  hosts:
  - kube_master

- name: zincati updates
  roles:
  - zincati
  hosts:
  - fedora_coreos_machines

- name: prepare k8s
  gather_facts:     False
  any_errors_fatal: True
  roles:
  - proxmox-prepare-k8s
  tags:
  - packages
  hosts:
  - flash_group_fcos

- name: apply quirks 
  roles:
  - fcos-quirks
  tags:
  - quirks
  hosts:
  - flash_group_fcos

- name: apply quirks for kernel
  hosts:
  - dynamic_fedora_coreos_machines
  roles:
  - fcos-quirks-kernel
  tags:
  - kernel-quirks
