- name: "get installed os-tree packages"
  command: bash -c "rpm-ostree  status --json|jq -r '.deployments[0].packages|join(\" \")'"
  register: os_tree

- set_fact:
    ostree_packages: "{{ os_tree.stdout.split(' ') }}"
    package_crio: 'cri-o'

- name: remove crio package if required
  command: "rpm-ostree uninstall cri-o"
  when: package_crio in ostree_packages and crio_replace

- name: reboot when cri-o was uninstalled in previous step
  reboot:
  when: package_crio in ostree_packages and crio_replace

- name: Check if already installed
  stat:
    path: "/bin/crio"
    get_attributes: no
    get_checksum: no
    get_mime: no
  register: need_package_crio

#- name: download cri-o
#  uri:
#    url:  "https://mirror.chpc.utah.edu/pub/fedora/linux/updates/34/Modular/x86_64/Packages/c/cri-o-{{ crio_version }}.x86_64.rpm"
#    dest: "/home/core/cri-o-{{ crio_version }}.x86_64.rpm"
#  ignore_errors: yes
#  when: not need_package_crio.stat.exists
#
#- name: "install cri-o"
#  command: "rpm-ostree install /home/core/cri-o-{{ crio_version }}.x86_64.rpm"
#  when: not need_package_crio.stat.exists and crio_replace

- name: create config for crio (missing in 1.24)
  copy:
    src:  "{{ item | basename }}"
    dest: "{{ item }}"
    owner: root
    group: root
    mode:  0644
  loop:
  - /etc/containers/storage.conf
- name: "install cri-o"
  command: "rpm-ostree ex module install cri-o:{{ crio_version }}"
  when: not need_package_crio.stat.exists and crio_replace

- name: "install cri-o"
  command: "rpm-ostree ex module enable cri-o:{{ crio_version }}"
  when: not need_package_crio.stat.exists and crio_replace


