- name: get kernel-release
  ansible.builtin.command: uname --kernel-release
  register: uname

- set_fact:
    current_kernel:  "{{ uname.stdout }}"

    current_kernel_version:  "{{ (uname.stdout.split('-')[0]).split('.') }}"
    current_package_version: "{{ (uname.stdout.split('-')[1]).split('.')[0] }}"
    current_fedora_version:  "{{ (uname.stdout.split('-')[1]).split('.')[1]| replace('fc','') }}"
 
    required_kernel_version:  "{{ (kernel_version.split('-')[0]).split('.') }}"
    required_package_version: "{{ (kernel_version.split('-')[1]).split('.')[0] }}"
    required_fedora_version:  "{{ (kernel_version.split('-')[1]).split('.')[1] |replace('fc', '') }}"

# Calculate unieque nummber for kernel version in order to compare versions
- set_fact:
    current_kernel_number: '{{ ((current_kernel_version[0]|int) * 256 * 256 + (current_kernel_version[1]|int ) * 256  + (current_kernel_version[2]|int)) * 1000 + current_package_version|int }}'
    required_kernel_number: '{{ ((required_kernel_version[0]|int) * 256 * 256 + (required_kernel_version[1]|int ) * 256  + (required_kernel_version[2]|int)) * 1000 + required_package_version|int }}'

#  with this it will only update when then required_kernel_number shows that the kernel is newer than the installed kernel  (no downgrades at this point!))
- set_fact:
    need_kernel_update: "{{ required_kernel_number > current_kernel_number }}"
  when: kernel_replace_policy_only_newer

- set_fact:
    need_kernel_update: "{{ required_kernel_number != current_kernel_number }}"
  when: not kernel_replace_policy_only_newer

- set_fact:
    kernel_packages:
    - "{{ kernel_url }}/k/kernel-{{ kernel_version }}.rpm"
    - "{{ kernel_url }}/k/kernel-core-{{ kernel_version }}.rpm"
    - "{{ kernel_url }}/k/kernel-modules-{{ kernel_version }}.rpm"


#- debug:
#    msg: "{{ current_kernel_number }} {{ required_kernel_number }}"
#
#- debug:
#    msg: "{{ required_kernel_version }} {{ required_package_version}} {{ required_fedora_version }}"
#
#- debug:
#    msg: "{{ current_kernel_version }} {{ current_package_version}} {{ current_fedora_version }}"
#
#- debug:
#    msg: "{{ need_kernel_update }}"
#- pause:

- name: download kernel, kernel-core and kernel-modules
  uri:
    url:  "{{ item }}"
    dest: "{{ download_dir }}/{{ item | basename }}"
  loop: "{{ kernel_packages }}"
  loop_control:
    label: "{{ item|basename }}"
  ignore_errors: yes
  when: need_kernel_update and kernel_replace
