- name: Check if already installed
  stat:
    path: "/bin/crio"
    get_attributes: no
    get_checksum: no
    get_mime: no
  register: need_package_crio

- name: download cri-o
  uri:
    url:  "https://mirror.chpc.utah.edu/pub/fedora/linux/updates/34/Modular/x86_64/Packages/c/cri-o-{{ crio_version }}.x86_64.rpm"
    dest: "/home/core/cri-o-{{ crio_version }}.x86_64.rpm"
  ignore_errors: yes
  when: not need_package_crio.stat.exists
