# Root cause
# https://github.com/kubernetes/kubernetes/issues/64315
# Solution:
# https://github.com/giantswarm/k8scloudconfig/blob/master/files/conf/hardening.conf#L4
# Other sources:
# https://gist.github.com/ntamvl/7c41acee650d376863fd940b99da836f

- name: set sysctl fs.inotify.max_user_watches
  ansible.posix.sysctl:
    sysctl_file: /etc/sysctl.d/k8s.conf
    name:  fs.inotify.max_user_watches
    value: "{{ fs_inotify_max_user_watches }}"
    state: present

- name: set sysctl fs.inotify.max_user_instances
  ansible.posix.sysctl:
    sysctl_file: /etc/sysctl.d/k8s.conf
    name:  fs.inotify.max_user_instances
    value: "{{ fs_inotify_max_user_instances }}"
    state: present
