- name: set sysctl fs.inotify.max_user_watches
  ansible.posix.sysctl:
    sysctl_file: /etc/sysctl.d/k8s.conf
    name:  fs.inotify.max_user_watches
    value: "{{ fs_inotify_max_user_watches }}"
    state: present

- name: set sysctl fs.inotify.max_user_instances
  ansible.posix.sysctl:
    sysctl_file: /etc/sysctl.d/k8s.conf
    name:  fs.inotify.max_user_instances
    value: "{{ fs_inotify_max_user_instances }}"
    state: present
