- name: disable zincati 
  ansible.builtin.systemd:
    name:   zincati
    masked: yes
  when: disable_zincati 

- name: enable zincati
  ansible.builtin.systemd:
    name:   zincati
    masked: no
  when: not disable_zincati
