
# There is a mean co-notation, when you provide with -e the flash_variable, it has the highest priority, so regardless, if you try
# to overrwirte it here, it will always be higher in priority, therefor no changes
- set_fact:
    # convert comma separated string to list and remove empty list items
    flash_list_processed: "{{ [] if (flash_list is not defined or flash_list == '') else (flash_list.split(',')|map('trim')|reject('equalto','')| list) }}"

#- debug:
#    msg: "{{ [] if (flash_list is not defined or flash_list == '') else flash_list.split(',')|map('trim')|reject('equalto','')|list }}"

#- debug:
#    msg: "{{ flash_list_processed }}"

#- debug:
#    msg: "{{ item }}"
#  loop: "{{ flash_list_processed }}"

- name: create list of kvm_id(s) and a list of ansible_host(s)
  set_fact:
    kvm_id_list:  "{{ kvm_id_list + [ item.value.kvm_id ] }}"
    ansible_host_list: "{{ ansible_host_list + [ item.value.ansible_host ] }}"
  loop: "{{ lookup('dict',  hostvars)  }}"
  when: "'kvm_id' in item.value"
  no_log: True

- name: create a list mac_address(es)
  set_fact:
    mac_address_list:  "{{ mac_address_list + [ item.value.mac_address ] }}"
  loop: "{{ lookup('dict',  hostvars) }}"
  when: "'mac_address' in item.value"
  no_log: True

- name: kvm_id must be unique for every host
  assert:
    that:
      - "{{ kvm_id_list|duplicate|length == 0 }}"
    msg: "hosts do not have a unique kvm_id: {{ kvm_id_list|duplicate }}"

- name: ansible_host must be unique for every host
  assert:
    that:
    - "{{ ansible_host_list|duplicate|length == 0 }}"
    msg: "hosts do not have a unique ip address in  ansible_host: {{ ansible_host_list|duplicate }}"

- name: mac_address must be unique for every host
  assert:
    that:
    - "{{ mac_address_list|duplicate|length == 0 }}"
    msg: "hosts do not have a unique mac address in mac_address: {{ mac_address_list|duplicate }}"


