#  Dynamic Global variables which will be used in subsequent scripts

#  fcos_flash_list         list of hosts which will be flashed

#  fcos_download_url       download_url for baremetal image
#  fcos_download_checksum  checksum for baremetal image

#  fcos_fcct_download_url  fcct down load url
#  fcos_fcct_filename      fcct filename
#
#  proxmox                 contains mac_address and real path to drivee


- name: create proxmox_create_kvm_list
  set_fact:
    proxmox_create_kvm_list: "{{ proxmox_create_kvm_list + [ hostvars[item] ] }}"
  loop: >- 
    {{ hostvars
       |filter_child_dictionary('kvm_host', inventory_hostname)
       |filter_child_dictionary('flash',    'True' )
       |list 
    }}

- name: report proxmox_guest_flash_list
  debug:
    msg: "{{ proxmox_create_kvm_list }}"
    verbosity: 2

- name: Create a directory if it does not exist
  file:
    path:  "{{ item }}"
    state: directory
    mode: '0700'
  loop: 
  - "{{ proxmox_create_kvm_tmp_dir }}"
  - "{{ proxmox_create_kvm_tmp_dir }}/bin"



