- name:    "create config file for systemd-timesyncd"
  template:
    src:   "{{ item | basename }}.jinja2"
    dest:  "{{ item }}"
    owner: root
    group: root
    mode:  0644
  loop:
  - "/etc/systemd/timesyncd.conf"
  register: proxmox_ntp

- name: "restart service systemd-timesyncd"
  service:
    name:  systemd-timesyncd
    state: restarted
  when:     proxmox_ntp.changed

