- name: apt update
  apt:
   cache_valid_time: 3600

- name: install packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - ethtool
    - vim
    - net-tools
    - sysfsutils
    # just auto-install packages
    - unattended-upgrades
    - apt-listchanges
#  when: proxmox_host_network_quirk == True
