kernel_replace: false
kernel_replace_policy_only_newer: false

#kernel_version: "5.14.7-200.fc34.x86_64"
#kernel_url:     "https://download-ib01.fedoraproject.org/pub/fedora/linux/updates/testing/34/Everything/x86_64/Packages/k"

#kernel_version: "5.12.19-300.fc34.x86_64"
#kernel_url:     "https://kojipkgs.fedoraproject.org//packages/kernel/5.12.19/300.fc34/x86_64"

kernel_version: "5.11.21-300.fc34.x86_64"
kernel_url:     "https://kojipkgs.fedoraproject.org//packages/kernel/5.11.21/300.fc34/x86_64"

download_dir: "/home/core"
