# FIXME you need to check if you can sync the stuff (do you have the key)

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ fcos_downloaddir }}/{{ item.channel }}"
    state: directory
    mode: '0755'
  loop: "{{ fcos_required_versions  }}"

- name: copy images to other hosts
  synchronize:
    src:  "{{ fcos_downloaddir }}/{{ item.channel }}/{{ item.filename }}"
    dest: "{{ fcos_downloaddir }}/{{ item.channel }}/{{ item.filename }}"
    mode: push
  delegate_to: "{{ download_hostname }}"
  when: inventory_hostname != download_hostname
  loop: "{{ fcos_required_versions  }}"
  loop_control:
    label: "{{ item.filename }}"
 
