- name: Create a directory if it does not exist
  file:
    path:  "{{ item }}"
    state: directory
    mode: '0700'
  loop:
  - "{{ proxmox_tmpdir }}"
  - "{{ proxmox_tmpdir }}/bin"
  when: proxmox_guests_list |length > 0
