# FIXME we might need to support different versions of fcct, depending on coreos version...
# FIXME no checksum on file, so actually if the file exists and a new version appears, we will not download it

#- uri:
#    url:            "https://api.github.com/repos/coreos/fcct/releases/latest"
#    body_format:    json
#    return_content: no          # json content will still be recorded
#  register: fcos_fcct_releases  #.json.assets

# Issues with json parsing --> you need to_json|from_json
# see https://github.com/ansible/ansible/issues/27299

- set_fact:
  #    fcos_fcct_download_url: "{{ fcos_fcct_releases.json|to_json|from_json|json_query(\"assets[?name=='fcct-x86_64-unknown-linux-gnu'].browser_download_url|@[0]\") }}"
    fcos_fcct_download_url: "https://github.com/coreos/fcct/releases/download/v0.7.0/fcct-x86_64-unknown-linux-gnu"
#  when: fcos_fcct_download_url == ""

- set_fact:
    # remove fcos_fcct_release
    fcos_fcct_releases:

- debug:
    msg: "{{ fcos_fcct_download_url }}"
#    verbosity: 2

- debug:
    msg: "{{ fcos_fcct_filename }}"
#    verbosity: 2

# Dirty catch if "dest" is a directory, the file will ALWAYS be downloaded
- name: download image if it doesn't exist or checksum does not match
  get_url:
    url:      "{{ fcos_fcct_download_url }}"
    dest:     "{{ fcos_bin_dir }}/{{ fcos_fcct_filename }}"
    force:    "no"
    mode:     "0755"
