# FIXME create subdir per fcos_channel (stable, testing, next)

- file:
    path:  "{{ fcos_downloaddir }}/{{ fcos_channel }}"
    owner: root
    group: root
    mode:  '0755'
    state: directory

- block:
  - debug:
      msg: "{{ inventory_hostname }}"

  - name: stat filename
    stat:
      path: "{{ fcos_downloaddir }}/{{ fcos_channel }}/{{ fcos_latest_versions[fcos_channel].filename }}"
    register: coreos_latest_filename

  - name: download image if it doesn't exist or checksum does not match
    get_url:
      url:      "{{ fcos_latest_versions[fcos_channel].download_url }}"
      dest:     "{{ fcos_downloaddir }}/{{ fcos_channel }}/{{ fcos_latest_versions[fcos_channel].filename }}"
      checksum: "{{ fcos_latest_versions[fcos_channel].checksum }}"
      force:    "no"
    when: not coreos_latest_filename.stat.exists

  - name: all image files, in order to expire (remove) them if they are too old
    find:
      paths: "{{ [ fcos_downloaddir, fcos_channel ]|join('/') }}"
      #patterns: "*.raw.xz"
      patterns: "*.xz"
    register: all_versions
    changed_when: False

  # scope of this block
  when: inventory_hostname == download_hostname

- name: Copy the file to the target hosts which avoids another download
  synchronize:
    src:  "{{ fcos_downloaddir }}/{{ fcos_channel }}/{{ fcos_latest_versions[fcos_channel].filename }}"
    dest: "{{ fcos_downloaddir }}/{{ fcos_channel }}/{{ fcos_latest_versions[fcos_channel].filename  }}"
    mode: push
  delegate_to: "{{ download_hostname }}"
  when: inventory_hostname != download_hostname

