- name: execute flash-fcos script
  command: "{{ proxmox_tmpdir }}/{{hostvars[item].kvm_id }}/flash-fcos"
  when: "'os_name' in hostvars[item] and hostvars[item].os_name == 'fcos'"
  loop: "{{ flash_list }}"
