- name: run script to gather information from proxmox
  command: "{{ proxmox_tmpdir }}/proxmox-to-json"
  register: proxmox_information
  changed_when: false

- name: put information into proxmox_host_guests variable
  set_fact:
    proxmox_host_guests: "{{ proxmox_information.stdout | from_json }}"

- name: remove proxmox_information variable
  set_fact:
    proxmox_information:

- name: join information 
  action: proxmox-cluster

#- name: delete temporary script directory
#  file:
#    dest:  "{{ proxmox_tmpdir }}"
#    state: absent
