- set_fact:
    systemd_services:
    - "/etc/systemd/system/fedora-cloud-sync-external.service"
    #- "/etc/systemd/system/fedora-cloud-sync-local.service"
    systemd_timers:
    - "/etc/systemd/system/fedora-cloud-sync-external.timer"
    #- "/etc/systemd/system/fedora-cloud-sync-local.timer"
    file_list:
    - "/usr/local/bin/fedora-cloud-sync-external.sh"

- name: Remove scripts which on host which are not a download host
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ file_list }}"
  when:
  -  inventory_hostname != download_host

- name: Disable timers which are not on download_host
  ansible.builtin.systemd:
    name:    "{{ item | basename }}"
    state:   stopped
    enabled: no
  loop: "{{ systemd_timers }}"
  when:
  - inventory_hostname != download_host
  ignore_errors: yes

- name: Remove services/timers on hosts which are not a download host
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ systemd_timers + systemd_services }}"
  when:
  - inventory_hostname != download_host

- name: Install services/timers
  template:
    src:  "{{ item | basename }}.jinja2"
    dest: "{{ item }}"
    owner: root
    group: root
    mode:  0644
  loop: "{{ systemd_services + systemd_timers }}"
  when: 
  - inventory_hostname == download_host

- name: Install scripts for external sync
  copy:
    src:  "{{ item | basename }}"
    dest: "{{ item }}"
    owner: root
    group: root
    mode:  0755
  loop: "{{ file_list }}"
  when: 
  - inventory_hostname == download_host

- name: Enable and Start timers
  ansible.builtin.systemd:
    name:    "{{ item | basename }}"
    state:   started
    enabled: yes
  loop: "{{ systemd_timers }}"
  when:
  - inventory_hostname == download_host
  ignore_errors: yes

