fcos_channel: "stable" # ['stable', 'testing', 'next']
fcos_download_url: ""
#fcos_download_url: "https://direct.link"

fcos_root_dir: "/ftp/pub/linux/fcos"
fcos_bin_dir:  "/ftp/pub/linux/fcos"

fcos_ssh_authorized_keys_dir: "sshkeys"
fcos_sshkeys: []

fcos_cacerts_dir: "cacerts"
fcos_cacerts: []

fcos_flash_list: []
fcos_tmp_dir: "/tmp/fcos"

# Additional packages to install
fcos_install_packages: 
- audit
- python3
- pip
- libselinux-python3 
- ethtool
- ipset
#- dbus-tools

fcos_machines: []

#machines:
#- ansible_host: 192.168.178.11
#  mac_address:  "0a:0b:0c:0d:0e:0f"
#  netmask: 16
#  gateway: 192.168.178.1
#
#- ansible_host: 192.168.178.12
#  mac_address:  "01:0b:0c:0d:0e:0f"
#  netmask: 16
#  gateway: 192.168.178.1

#fcos_nameservers: []
fcos_nameservers: 
- 192.168.178.1
- 192.168.178.3
fcos_netmask: 24
fcos_ssh_authorized_keys: []

#search: []
search:
- fritz.box
- prod.fritz.box
- dev.fritz.box
- ops.fritz.box

fcos_override_sysconfig_docker: True
